default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: cr_o_rdc_development
test:
  <<: *default
  database: cr_o_rdc_test

production:
  <<: *default
  database: cr_o_rdc_production
